version: '3.8'

services:

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - "app"
      - "server"

  app:
    image: todo-front
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8080/api"
    container_name: todo-front

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo_data:/data/db

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data

  server:
    image: todo-back
    build: 
      context: ./todo-backend
      dockerfile: Dockerfile
    depends_on:
      - "redis"
      - "mongo"
    environment:
      PORT: 3001
      REDIS_URL: "redis://redis:6379"
      MONGO_URL: "mongodb://the_username:the_password@mongo:27017/the_database"
    container_name: todo-back
